services:
  kastmates-flutter:
    image: kastmates-flutter
    container_name: kastmates-flutter
    build:
      context: .
      # target: builder
    volumes:
      - .:/code
      - vscode-server:/root/.vscode-server
    stdin_open: true
    tty: true
    ports:
      - "8085:8085" # flutter
      - "8081:8081" # debug
    working_dir: /code/app
    command: /bin/bash
    # command: fwr
    # command: flutter run -d web-server --web-hostname=0.0.0.0 --web-port=8085 --start-paused

volumes:
  vscode-server:
    name: vscode-server
    external: true